services:
  - type: web
    name: xrp-miner
    env: node
    buildCommand: npm install
    startCommand: node dist/index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
